export const SELECT_SAVED_RESTAURANT = 'SELECT_SAVED_RESTAURANT';
export const DELETE_RESTAURANT = 'DELETE_RESTAURANT';
export const DELETE_SAVED_RESTAURANT = 'DELETE_SAVED_RESTAURANT';
export const GET_RESTAURANTS = 'GET_RESTAURANTS';
export const GET_USER = 'GET_USER';
export const POST_TO_YELP = 'POST_TO_YELP';
